CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT      NOT NULL UNIQUE,
    password_hash TEXT      NOT NULL,
    roles         TEXT      NOT NULL DEFAULT 'ROLE_USER',
    created_at    TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bank_links (
user_id     BIGINT      NOT NULL,
bank        VARCHAR(32) NOT NULL,         -- vbank/abank/sbank
client_id   VARCHAR(128) NOT NULL,
access_token TEXT        NOT NULL,
expires_at   TIMESTAMP   NOT NULL,
PRIMARY KEY (user_id, bank),
CONSTRAINT fk_bank_links_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bank_links_expires_at ON bank_links(expires_at);

CREATE TABLE IF NOT EXISTS accounts (
id              BIGSERIAL PRIMARY KEY,
user_id         BIGINT       NOT NULL,
bank            VARCHAR(32)  NOT NULL,
account_id      VARCHAR(64)  NOT NULL,
nickname        VARCHAR(128),
is_reserve      BOOLEAN      NOT NULL DEFAULT FALSE,
is_salary_source BOOLEAN     NOT NULL DEFAULT FALSE,
created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
updated_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
CONSTRAINT uq_accounts UNIQUE (user_id, bank, account_id),
CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_accounts_user ON accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_accounts_user_salary ON accounts(user_id, is_salary_source);
CREATE INDEX IF NOT EXISTS idx_accounts_user_reserve ON accounts(user_id, is_reserve);

-- триггер для updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_accounts_updated_at ON accounts;
CREATE TRIGGER trg_accounts_updated_at
BEFORE UPDATE ON accounts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
